name: download mp3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
         sudo apt-get install ffmpeg
         pip3 install -U youtube-dl
         youtube-dl --extract-audio --audio-format mp3 --prefer-ffmpeg $(cat < file.txt)
         mv *.mp3 song.mp3
      - uses: actions/upload-artifact@v2
        with:
             name: Song
             path: song.mp3
